services:
  stp:
    build: .
    volumes:
      - ./etc:/etc/osmocom
    networks:
      xxx:
        ipv4_address: 10.1.0.15
    entrypoint: osmo-stp -c /etc/osmocom/osmo-stp.cfg

  cn-msc:
    build: .
    volumes:
      - ./etc:/etc/osmocom
    networks:
      xxx:
        ipv4_address: 10.1.0.13
    entrypoint: osmo-msc -c /etc/osmocom/osmo-msc.cfg

  cn-hlr:
    build: .
    volumes:
      - ./etc:/etc/osmocom
      # TODO: hlr.db
    networks:
      xxx:
        ipv4_address: 10.1.0.14
    entrypoint: osmo-hlr -c /etc/osmocom/osmo-hlr.cfg -l /var/lib/osmocom/hlr.db

  ran-bts-trx:
    build: .
    volumes:
      - ./etc:/etc/osmocom
    networks:
      xxx:
        ipv4_address: 10.1.0.10
    entrypoint: osmo-bts-trx -c /etc/osmocom/osmo-bts-trx.cfg

  ran-trx-lms:
    build: .
    volumes:
      - ./etc:/etc/osmocom
    devices:
      - /dev/bus/usb/002/004
    networks:
      xxx:
        ipv4_address: 10.1.0.11
    entrypoint: osmo-trx-lms -C /etc/osmocom/osmo-trx-lms.cfg

  ran-bsc:
    build: .
    volumes:
      - ./etc:/etc/osmocom
    networks:
      xxx:
        ipv4_address: 10.1.0.12
    entrypoint: osmo-bsc -c /etc/osmocom/osmo-bsc.cfg

networks:
  xxx:
    ipam:
      config:
        - subnet: 10.1.0.0/24
